In [ ]:
import pandas as pd

# Load training data
s1 = pd.read_csv("../dataset/train/train_source1.tsv", sep="\t")
s2 = pd.read_csv("../dataset/train/train_source2.tsv", sep="\t")
s3 = pd.read_csv("../dataset/train/train_source3.tsv", sep="\t")
gt = pd.read_csv("../dataset/train/train_ground_truth.tsv", sep="\t")

print("S1 shape:", s1.shape)
print("S2 shape:", s2.shape)
print("S3 shape:", s3.shape)
print("Ground Truth shape:", gt.shape)

S1 shape: (2206821, 4)
S2 shape: (5034616, 4)
S3 shape: (5285603, 4)
Ground Truth shape: (2206821, 2)

In [9]:
display(s1.head())
display(s2.head())
display(s3.head())
display(gt.head())

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India

,entity_id,business_name,business_address,country
0,S2-166376419,राम मार्केटिंग प्राइवेट लिमिटेड,"KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",India
1,S2-764573417,-- Holloway Peak Inc Seafood,"105 ELM ST, MORGANTON, NC",US
2,S2-639257739,आदित्य प्रॉपर्टीज एलएलपी,"G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh",India
3,S2-163963287,Summit Inc,"GREENSBORO, NC, 19 1/2 STARDUST TRAIL",US
4,S2-49942811,Delta Tetlecommunication Inc,"914 PIERPONT AVE, CLEVELAND, OH",US

,entity_id,business_name,business_address,country
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US
1,S3-859268022,International South Consultants Private Ltd,NaN,India
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

In [10]:
print("S1 columns:", s1.columns.tolist())
print("S2 columns:", s2.columns.tolist())
print("S3 columns:", s3.columns.tolist())
print("GT columns:", gt.columns.tolist())

S1 columns: ['entity_id', 'business_name', 'business_address', 'country']
S2 columns: ['entity_id', 'business_name', 'business_address', 'country']
S3 columns: ['entity_id', 'business_name', 'business_address', 'country']
GT columns: ['source1_entity_id', 'matched_entity_ids']

In [11]:
print("S1 missing:")
display(s1.isnull().sum())

print("S2 missing:")
display(s2.isnull().sum())

print("S3 missing:")
display(s3.isnull().sum())

print("Ground Truth missing:")
display(gt.isnull().sum())

S1 missing:

entity_id           0
business_name       0
business_address    0
country             0
dtype: int64

S2 missing:

entity_id                0
business_name            2
business_address    168967
country                  0
dtype: int64

S3 missing:

entity_id                0
business_name           13
business_address    175916
country                  0
dtype: int64

Ground Truth missing:

source1_entity_id          0
matched_entity_ids    123247
dtype: int64

In [12]:
gt.head(20)

   source1_entity_id                                 matched_entity_ids
0          S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1        S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2       S1-343815751             S2-790675320,S2-479876582,S3-878454467
3       S1-656753428              S2-153058913,S2-24659151,S3-679606215
4       S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...
5        S1-18727616  S2-755677256,S3-187831601,S3-641489370,S3-4762...
6       S1-318373630                          S2-660036492,S3-804600254
7        S1-86989137                          S3-274817120,S3-312496301
8        S1-29845983                          S2-648035184,S3-588502663
9       S1-789009573              S2-383871912,S3-74481402,S3-576451439
10      S1-730934468                          S2-356983532,S3-352439310
11        S1-7293388  S2-7028416,S2-442723188,S2-157073701,S3-523120965
12      S1-546142636  S2-487600131,S2-582477216,S2-392804085,S3-2000...
13      S1-274126313  S2-736616474,S2-680265918,S2-51486805,S3-92563...
14      S1-145361722              S2-120366543,S2-939389287,S3-96572514
15      S1-503957000  S2-994658326,S2-235117490,S2-353308450,S2-1732...
16      S1-692000596                          S2-580419223,S3-164220452
17      S1-561341312                          S2-483615364,S3-619529814
18      S1-777597828                          S2-836452886,S3-413669121
19      S1-282467635                          S2-938895481,S3-138350041

In [13]:
print("S1:")
print(s1.columns.tolist())

print("\nS2:")
print(s2.columns.tolist())

print("\nS3:")
print(s3.columns.tolist())

print("\nGround Truth:")
print(gt.columns.tolist())

S1:
['entity_id', 'business_name', 'business_address', 'country']

S2:
['entity_id', 'business_name', 'business_address', 'country']

S3:
['entity_id', 'business_name', 'business_address', 'country']

Ground Truth:
['source1_entity_id', 'matched_entity_ids']

In [14]:
print("S1:")
print(s1.dtypes)

print("\nS2:")
print(s2.dtypes)

print("\nS3:")
print(s3.dtypes)

print("\nGround Truth:")
print(gt.dtypes)

S1:
entity_id           object
business_name       object
business_address    object
country             object
dtype: object

S2:
entity_id           object
business_name       object
business_address    object
country             object
dtype: object

S3:
entity_id           object
business_name       object
business_address    object
country             object
dtype: object

Ground Truth:
source1_entity_id     object
matched_entity_ids    object
dtype: object

In [15]:
import numpy as np

gt["num_matches"] = (
    gt["matched_entity_ids"]
    .fillna("")
    .apply(lambda x: 0 if x == "" else len(x.split(",")))
)

gt["num_matches"].describe()

count    2.206821e+06
mean     3.461253e+00
std      1.705323e+00
min      0.000000e+00
25%      2.000000e+00
50%      3.000000e+00
75%      5.000000e+00
max      1.100000e+01
Name: num_matches, dtype: float64

In [16]:
gt["num_matches"].value_counts().sort_index().head(30)

num_matches
0     123247
1     119157
2     375212
3     530841
4     484115
5     321957
6     164868
7      63968
8      18680
9       4205
10       534
11        37
Name: count, dtype: int64

In [17]:
def count_source_matches(x):
    if pd.isna(x) or x == "":
        return pd.Series({"S2": 0, "S3": 0})
    
    ids = x.split(",")
    
    return pd.Series({
        "S2": sum(i.startswith("S2-") for i in ids),
        "S3": sum(i.startswith("S3-") for i in ids)
    })

source_counts = gt["matched_entity_ids"].apply(count_source_matches)

source_counts.sum()

KeyboardInterrupt

In [18]:
print("S1:", s1.shape)
print("S2:", s2.shape)
print("S3:", s3.shape)
print("GT:", gt.shape)

print("\nCountries:")
print(s1["country"].value_counts())

S1: (2206821, 4)
S2: (5034616, 4)
S3: (5285603, 4)
GT: (2206821, 3)

Countries:
country
US       1323633
India     883188
Name: count, dtype: int64

In [19]:
print("Missing addresses:")
print("S2:", s2["business_address"].isna().sum())
print("S3:", s3["business_address"].isna().sum())

Missing addresses:
S2: 168967
S3: 175916

In [1]:
import pandas as pd
import numpy as np

In [2]:
gt = pd.read_csv(
    "../dataset/train/train_ground_truth.tsv",
    sep="\t"
)

print(gt.shape)
print(gt.columns.tolist())

(2206821, 2)
['source1_entity_id', 'matched_entity_ids']

In [3]:
gt.head(10)

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...
5       S1-18727616  S2-755677256,S3-187831601,S3-641489370,S3-4762...
6      S1-318373630                          S2-660036492,S3-804600254
7       S1-86989137                          S3-274817120,S3-312496301
8       S1-29845983                          S2-648035184,S3-588502663
9      S1-789009573              S2-383871912,S3-74481402,S3-576451439

In [4]:
def parse_matches(value):
    if pd.isna(value) or str(value).strip() == "":
        return set()
    
    return set(
        x.strip()
        for x in str(value).split(",")
        if x.strip()
    )

gt["true_matches"] = gt["matched_entity_ids"].apply(parse_matches)

In [5]:
gt[["source1_entity_id", "true_matches"]].head()

  source1_entity_id                                       true_matches
0         S1-965667  {S2-681193310, S2-743505751, S3-860443364, S3-...
1       S1-55344266  {S2-249013014, S3-478195123, S2-197070651, S3-...
2      S1-343815751         {S3-878454467, S2-479876582, S2-790675320}
3      S1-656753428          {S2-153058913, S2-24659151, S3-679606215}
4      S1-102811957  {S3-449308785, S3-728090388, S3-928796641, S2-...

In [6]:
def calculate_f05(true_matches, predicted_matches):
    true_matches = set(true_matches)
    predicted_matches = set(predicted_matches)

    tp = len(true_matches & predicted_matches)
    fp = len(predicted_matches - true_matches)
    fn = len(true_matches - predicted_matches)

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0

    beta = 0.5

    if precision == 0 and recall == 0:
        f05 = 0.0
    else:
        f05 = (
            (1 + beta**2) * precision * recall
            / ((beta**2 * precision) + recall)
        )

    return precision, recall, f05

In [7]:
calculate_f05(
    {"S2-A", "S2-B"},
    {"S2-A", "S2-C"}
)

(0.5, 0.5, 0.5)

In [8]:
print("Exact:", calculate_f05({"A", "B"}, {"A", "B"}))

print("Wrong:", calculate_f05({"A", "B"}, {"C", "D"}))

print("Partial:", calculate_f05({"A", "B"}, {"A", "C"}))

print("True no-match:", calculate_f05(set(), set()))

print("False positive on no-match:", calculate_f05(set(), {"A"}))

Exact: (1.0, 1.0, 1.0)
Wrong: (0.0, 0.0, 0.0)
Partial: (0.5, 0.5, 0.5)
True no-match: (0.0, 0.0, 0.0)
False positive on no-match: (0.0, 0.0, 0.0)

In [9]:
# Number of S1 entities with zero true matches
zero_match_count = (gt["true_matches"].apply(len) == 0).sum()

# Number with at least one true match
matched_count = (gt["true_matches"].apply(len) > 0).sum()

print("S1 with zero matches:", zero_match_count)
print("S1 with >=1 match:", matched_count)
print("Total S1:", len(gt))

S1 with zero matches: 123247
S1 with >=1 match: 2083574
Total S1: 2206821

In [10]:
# Take 5 real S1 entities
test_gt = gt[["source1_entity_id", "true_matches"]].head(5).copy()

# Create deliberately imperfect predictions
test_predictions = {
    test_gt.iloc[0]["source1_entity_id"]: test_gt.iloc[0]["true_matches"],  # perfect
    test_gt.iloc[1]["source1_entity_id"]: set(),                           # predict no match
    test_gt.iloc[2]["source1_entity_id"]: {"FAKE-ID"},                     # wrong
    test_gt.iloc[3]["source1_entity_id"]: set(list(test_gt.iloc[3]["true_matches"])[:1]), # partial
    test_gt.iloc[4]["source1_entity_id"]: test_gt.iloc[4]["true_matches"] | {"FAKE-ID"}   # extra false positive
}

In [11]:
results = []

for _, row in test_gt.iterrows():
    s1_id = row["source1_entity_id"]
    true_matches = row["true_matches"]
    predicted_matches = test_predictions.get(s1_id, set())

    precision, recall, f05 = calculate_f05(
        true_matches,
        predicted_matches
    )

    results.append({
        "source1_entity_id": s1_id,
        "precision": precision,
        "recall": recall,
        "f05": f05
    })

results_df = pd.DataFrame(results)

results_df

  source1_entity_id  precision    recall       f05
0         S1-965667   1.000000  1.000000  1.000000
1       S1-55344266   0.000000  0.000000  0.000000
2      S1-343815751   0.000000  0.000000  0.000000
3      S1-656753428   1.000000  0.333333  0.714286
4      S1-102811957   0.857143  1.000000  0.882353

In [12]:
print("Macro Precision:", results_df["precision"].mean())
print("Macro Recall:", results_df["recall"].mean())
print("Macro F0.5:", results_df["f05"].mean())

Macro Precision: 0.5714285714285714
Macro Recall: 0.4666666666666666
Macro F0.5: 0.519327731092437

In [15]:
def evaluate_predictions(ground_truth, predictions):
    """
    Evaluate predictions using per-S1 precision, recall and F0.5,
    then macro-average across all S1 entities.

    predictions:
        Dictionary:
        {
            "S1-ID": {"S2-ID", "S3-ID", ...}
        }
    """

    results = []

    for _, row in ground_truth.iterrows():

        s1_id = row["source1_entity_id"]
        true_matches = row["true_matches"]

        # If our model didn't predict anything for this S1,
        # treat it as an empty prediction.
        predicted_matches = predictions.get(s1_id, set())

        precision, recall, f05 = calculate_f05(
            true_matches,
            predicted_matches
        )

        results.append({
            "source1_entity_id": s1_id,
            "precision": precision,
            "recall": recall,
            "f05": f05
        })

    results_df = pd.DataFrame(results)

    metrics = {
        "macro_precision": results_df["precision"].mean(),
        "macro_recall": results_df["recall"].mean(),
        "macro_f05": results_df["f05"].mean()
    }

    return results_df, metrics

In [16]:
results_df, metrics = evaluate_predictions(
    test_gt,
    test_predictions
)

print("Macro Precision:", metrics["macro_precision"])
print("Macro Recall:", metrics["macro_recall"])
print("Macro F0.5:", metrics["macro_f05"])

Macro Precision: 0.5714285714285714
Macro Recall: 0.4666666666666666
Macro F0.5: 0.519327731092437

In [17]:
VALIDATION_SIZE = 10000

validation_gt = gt.sample(
    n=VALIDATION_SIZE,
    random_state=42
).copy()

print(validation_gt.shape)

(10000, 3)

In [20]:
validation_gt[
    ["source1_entity_id"]
].to_csv(
    "../experiments/validation_s1_ids.csv",
    index=False
)

In [19]:
import os

os.makedirs("../experiments", exist_ok=True)

In [21]:
import os

os.makedirs("../experiments", exist_ok=True)

In [22]:
VALIDATION_SIZE = 10000

validation_gt = gt.sample(
    n=VALIDATION_SIZE,
    random_state=42
).copy()

print("Validation size:", len(validation_gt))

Validation size: 10000

In [23]:
validation_gt[["source1_entity_id"]].to_csv(
    "../experiments/validation_s1_ids.csv",
    index=False
)

print("Saved validation IDs.")

Saved validation IDs.

In [24]:
validation_ids = pd.read_csv(
    "../experiments/validation_s1_ids.csv"
)

print(validation_ids.shape)
print(validation_ids.head())

(10000, 1)
  source1_entity_id
0      S1-384734976
1      S1-574038342
2      S1-189408085
3      S1-797774718
4      S1-729164458

In [1]:
import os
from pathlib import Path

print("Current directory:")
print(os.getcwd())

Current directory:
C:\Users\katku\OneDrive\Desktop\ML Challenge\student_resource\notebooks

In [2]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

print(PROJECT_ROOT)

C:\Users\katku\OneDrive\Desktop\ML Challenge\student_resource

In [2]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.evaluation import (
    parse_matches,
    precision_recall_f05,
    evaluate_predictions,
)

print("Evaluation module imported successfully!")

Evaluation module imported successfully!

In [3]:
precision_recall_f05(
    {"S2-1", "S3-1"},
    {"S2-1", "S3-1"}
)

(1.0, 1.0, 1.0)

In [4]:
precision_recall_f05(
    {"S2-1"},
    {"S2-1", "S3-1", "S3-2"}
)

(1.0, 0.3333333333333333, 0.7142857142857143)

In [5]:
import pandas as pd

gt_path = PROJECT_ROOT / "dataset" / "train" / "train_ground_truth.tsv"

gt = pd.read_csv(
    gt_path,
    sep="\t"
)

print("Shape:", gt.shape)
print(gt.head())

Shape: (2206821, 2)
  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

In [6]:
print(gt["matched_entity_ids"].isna().sum())

123247

In [7]:
print(gt["source1_entity_id"].isna().sum())

0

In [8]:
gt_sample = gt.sample(
    n=10000,
    random_state=42
).copy()

print(gt_sample.shape)

(10000, 2)

In [9]:
perfect_predictions = gt_sample.copy()

In [10]:
results, metrics = evaluate_predictions(
    gt_sample,
    perfect_predictions
)

print(metrics)

{'macro_precision': np.float64(1.0), 'macro_recall': np.float64(1.0), 'macro_f05': np.float64(1.0)}

In [11]:
zero_predictions = gt_sample.copy()

zero_predictions["matched_entity_ids"] = ""

In [12]:
results, metrics = evaluate_predictions(
    gt_sample,
    zero_predictions
)

print(metrics)

{'macro_precision': np.float64(0.0557), 'macro_recall': np.float64(0.0557), 'macro_f05': np.float64(0.0557)}

In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.evaluation import (
    parse_matches,
    precision_recall_f05,
    evaluate_predictions,
)

print("Evaluation module imported successfully!")

Evaluation module imported successfully!

In [2]:
gt_sample = gt.sample(
    n=10000,
    random_state=42
).copy()

NameError: name 'gt' is not defined

In [3]:
gt_sample

NameError: name 'gt_sample' is not defined

In [5]:
import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

print(PROJECT_ROOT)

C:\Users\katku\OneDrive\Desktop\ML Challenge\student_resource

In [6]:
gt_path = PROJECT_ROOT / "dataset" / "train" / "train_ground_truth.tsv"

gt = pd.read_csv(
    gt_path,
    sep="\t"
)

print("Shape:", gt.shape)
print(gt.head())

Shape: (2206821, 2)
  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

In [7]:
gt_sample = gt.sample(
    n=10000,
    random_state=42
).copy()

print(gt_sample.shape)

(10000, 2)

In [8]:
perfect_predictions = gt_sample.copy()

results, metrics = evaluate_predictions(
    gt_sample,
    perfect_predictions
)

print(metrics)

{'macro_precision': np.float64(1.0), 'macro_recall': np.float64(1.0), 'macro_f05': np.float64(1.0)}

In [9]:
from src.evaluation import (
    parse_matches,
    precision_recall_f05,
    evaluate_predictions,
)

In [10]:
import time

start = time.time()

results, metrics = evaluate_predictions(
    gt,
    gt
)

elapsed = time.time() - start

print("Metrics:")
print(metrics)

print(f"\nRuntime: {elapsed:.2f} seconds")

Metrics:
{'macro_precision': np.float64(1.0), 'macro_recall': np.float64(1.0), 'macro_f05': np.float64(1.0)}

Runtime: 51.27 seconds

In [11]:
print(results.shape)
print(results.head())

(2206821, 4)
  source1_entity_id  precision  recall  f05
0         S1-965667        1.0     1.0  1.0
1       S1-55344266        1.0     1.0  1.0
2      S1-343815751        1.0     1.0  1.0
3      S1-656753428        1.0     1.0  1.0
4      S1-102811957        1.0     1.0  1.0

In [ ]:
gt["actual_set"] = gt["matched_entity_ids"].map(parse_matches)

print(
    "No-match S1:",
    (gt["actual_set"].map(len) == 0).sum()
)

In [1]:
import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

test_s1 = pd.read_csv(
    PROJECT_ROOT / "dataset" / "test" / "test_source1.tsv",
    sep="\t"
)

test_s2 = pd.read_csv(
    PROJECT_ROOT / "dataset" / "test" / "test_source2.tsv",
    sep="\t"
)

test_s3 = pd.read_csv(
    PROJECT_ROOT / "dataset" / "test" / "test_source3.tsv",
    sep="\t"
)

print("S1:", test_s1.shape)
print("S2:", test_s2.shape)
print("S3:", test_s3.shape)

S1: (1732544, 4)
S2: (4887273, 4)
S3: (5082316, 4)

In [2]:
print(test_s1.head())
print(test_s2.head())
print(test_s3.head())

      entity_id         business_name  \
0  S1-714132312       Zephay Labs Inc
1  S1-106407869  Vision Partners Corp
2  S1-156285671         << Team Ecole
3  S1-689823050   Red Perfect Trading
4  S1-921369899         ZNB Club SARL

                                    business_address country
0                        2621 Cotten Road, Tyler, TX      US
1             IA, Iowa City, 1064 Newton Rd, Unit 11      US
2  175 Boulevard du Président Franklin Roosevelt,...  France
3  Mirzapur, Ews 12, Uttar Pradesh, Mirzapursadar...   India
4  Nouvelle-Aquitaine, La Teste-de-Buch, 5 bis Ru...  France
      entity_id             business_name  \
0  S2-192345572           Brahma Infosoft
1  S2-566025912  Marina Ecole France Sarl
2  S2-158121477          SCI Ptit Àmicale
3   S2-89663826               Apex Summit
4  S2-884102769              Fresh Truist

                                    business_address country
0  COIMATORE COLONY, HUNSUR TQMYSORE DIST., Karna...   India
1            63 R. DE DIEPPE, LILLE, Hauts-de-France  France
2                    18 RUE JEN ZAY, Dunkerque, Nord  France
3                   67 KENTUCKY ST, SALYERSVILLE, KY      US
4               8264 FILLY COURT, ROANOKE COUNTY, VA      US
      entity_id                               business_name  \
0  S3-462677478                              मॉडर्न फाइनेंस
1  S3-374810425                       Shri Sai Infratech Co
2  S3-198586129                 Fractales Amis Groupe S.A.S
3   S3-10300249  Shri Supreme Consulting Private  (Limited)
4  S3-604980231        Prime Realty Ventures Public Limited

                                    business_address country
0  No 10 Enkay Square, 448A, Udyog Vihar Phase V,...   India
1                              3/115, East Delhi, DL   India
2            23 Rue Icmre, La Teste-de-buch, Gironde  France
3                H.no 910 A 3503, Mumbai, महाराष्ट्र   India
4  G.t. Karnal Road, Industrial Area, New Delhi, ...   India

In [3]:
print("Number of test S1 IDs:", test_s1["entity_id"].nunique())
print("Number of test S1 rows:", len(test_s1))
print("Duplicate S1 IDs:", test_s1["entity_id"].duplicated().sum())

Number of test S1 IDs: 1732544
Number of test S1 rows: 1732544
Duplicate S1 IDs: 0

In [4]:
def validate_submission(predictions, test_s1, test_s2, test_s3):

    print("========== SUBMISSION CHECK ==========")

    # Required columns
    required = {
        "source1_entity_id",
        "matched_entity_ids"
    }

    missing_columns = required - set(predictions.columns)

    if missing_columns:
        print("❌ Missing columns:", missing_columns)
        return False

    print("✅ Required columns present")

    # S1 IDs
    required_s1 = set(test_s1["entity_id"])
    predicted_s1 = set(predictions["source1_entity_id"])

    # Duplicates
    duplicates = predictions[
        "source1_entity_id"
    ].duplicated().sum()

    print("Duplicate S1 rows:", duplicates)

    if duplicates > 0:
        print("❌ Duplicate S1 IDs")
        return False

    # Missing S1
    missing_s1 = required_s1 - predicted_s1

    print("Missing S1 IDs:", len(missing_s1))

    if missing_s1:
        print("❌ Missing test S1 entities")
        return False

    # Extra S1
    extra_s1 = predicted_s1 - required_s1

    print("Extra S1 IDs:", len(extra_s1))

    if extra_s1:
        print("❌ Unknown S1 IDs")
        return False

    # Valid S2/S3 IDs
    valid_targets = set(test_s2["entity_id"]) | set(test_s3["entity_id"])

    invalid_targets = set()

    for value in predictions["matched_entity_ids"].fillna(""):

        value = str(value).strip()

        if not value:
            continue

        for entity_id in value.split(","):

            entity_id = entity_id.strip()

            if entity_id and entity_id not in valid_targets:
                invalid_targets.add(entity_id)

    print("Invalid S2/S3 IDs:", len(invalid_targets))

    if invalid_targets:
        print("❌ Invalid target IDs")
        print(list(invalid_targets)[:10])
        return False

    print("\n✅ ALL BASIC CHECKS PASSED")

    return True

In [5]:
pred = pd.read_csv(
    "PATH_TO_RAJINI_TSV",
    sep="\t"
)

print(pred.shape)
print(pred.columns.tolist())
print(pred.head())

FileNotFoundError: [Errno 2] No such file or directory: 'PATH_TO_RAJINI_TSV'

In [6]:
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().parent

test_s1 = pd.read_csv(
    PROJECT_ROOT / "dataset" / "test" / "test_source1.tsv",
    sep="\t"
)

test_s2 = pd.read_csv(
    PROJECT_ROOT / "dataset" / "test" / "test_source2.tsv",
    sep="\t"
)

test_s3 = pd.read_csv(
    PROJECT_ROOT / "dataset" / "test" / "test_source3.tsv",
    sep="\t"
)

print("S1:", test_s1.shape)
print("S2:", test_s2.shape)
print("S3:", test_s3.shape)

S1: (1732544, 4)
S2: (4887273, 4)
S3: (5082316, 4)

In [7]:
print("Test S1 IDs:", test_s1["entity_id"].nunique())
print("Test S2 IDs:", test_s2["entity_id"].nunique())
print("Test S3 IDs:", test_s3["entity_id"].nunique())

print("S1 duplicates:", test_s1["entity_id"].duplicated().sum())
print("S2 duplicates:", test_s2["entity_id"].duplicated().sum())
print("S3 duplicates:", test_s3["entity_id"].duplicated().sum())

Test S1 IDs: 1732544
Test S2 IDs: 4887273
Test S3 IDs: 5082316
S1 duplicates: 0
S2 duplicates: 0
S3 duplicates: 0

In [8]:
output_dir = PROJECT_ROOT / "output"
output_dir.mkdir(exist_ok=True)

print(output_dir)

C:\Users\katku\OneDrive\Desktop\ML Challenge\student_resource\output

In [9]:
def inspect_prediction_file(path):
    pred = pd.read_csv(path, sep="\t")

    print("========== RAJINI FILE ==========")
    print("Shape:", pred.shape)
    print("Columns:", pred.columns.tolist())
    print("\nFirst 5 rows:")
    display(pred.head())

    print("\nMissing values:")
    print(pred.isna().sum())

    print("\nDuplicate rows:")
    print(pred.duplicated().sum())

    if "source1_entity_id" in pred.columns:
        print(
            "\nUnique S1 IDs:",
            pred["source1_entity_id"].nunique()
        )

    return pred

In [10]:
def prediction_summary(predictions):

    print("========== PREDICTION SUMMARY ==========")

    predictions = predictions.copy()

    predictions["matched_entity_ids"] = (
        predictions["matched_entity_ids"]
        .fillna("")
        .astype(str)
        .str.strip()
    )

    match_counts = predictions["matched_entity_ids"].apply(
        lambda x: 0 if not x else len(x.split(","))
    )

    print("Total S1 rows:", len(predictions))
    print("Unique S1 IDs:", predictions["source1_entity_id"].nunique())

    print("\nS1 entities with 0 matches:",
          (match_counts == 0).sum())

    print("S1 entities with >=1 match:",
          (match_counts >= 1).sum())

    print("\nTotal predicted matches:",
          match_counts.sum())

    print("\nMatch-count distribution:")
    print(match_counts.value_counts().sort_index())

    return match_counts

In [11]:
def check_target_sources(predictions, test_s2, test_s3):

    valid_s2 = set(test_s2["entity_id"])
    valid_s3 = set(test_s3["entity_id"])

    s2_count = 0
    s3_count = 0
    invalid_count = 0

    for value in predictions["matched_entity_ids"].fillna(""):

        value = str(value).strip()

        if not value:
            continue

        for entity_id in value.split(","):

            entity_id = entity_id.strip()

            if entity_id.startswith("S2-"):
                s2_count += 1

            elif entity_id.startswith("S3-"):
                s3_count += 1

            else:
                invalid_count += 1

    print("S2 predictions:", s2_count)
    print("S3 predictions:", s3_count)
    print("Invalid-format predictions:", invalid_count)